# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fe1bd870d4f2b1ba22669df2d0708ec3d4aa149a0b766418c11970c6c5ba7d8af55ce35446ac29931fc8412e09ef05e5bdbb15a406de1b0d8d0309ff7b282a0

test:
  secret_key_base: a0339b2da117947e53042c15a0b8f79f1aedbfad08d40a6f29721e01bf5838d29e329a6e5991c377253103f54fb68e4597643837d6c9d9f555f4632a6857b6ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
